@startuml
'Alice -> Bob: Authentication Request
'Bob --> Alice: Authentication Response
'
'Alice -> Bob: Another authentication Request
'Alice <-- Bob: another authentication Response

OkHttpClient -> Cache
Cache -> InternalCache
OkHttpClient -> RealCall
RealCall -> OkHttpClient:internalCache()
RealCall <-- InternalCache
RealCall -> CacheInterceptor

activate CacheInterceptor
CacheInterceptor -> CacheInterceptor:intercept()
CacheInterceptor -> InternalCache:get()
InternalCache -> Cache:get()
CacheInterceptor -> CacheStrategy
CacheInterceptor -> InternalCache:put()
InternalCache -> Cache:put()
InternalCache -> CacheRequestImpl:body()
RealCall <<-- CacheInterceptor
deactivate CacheInterceptor

@enduml